{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/buse22/IE221-TeamWork-Group07/blob/main/Untitled3.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy import stats\n",
        "\n",
        "np.random.seed(42)\n",
        "\n",
        "# --------- Distributions ----------\n",
        "def rvs_uniform(size):\n",
        "    return np.random.uniform(0, 1, size)\n",
        "\n",
        "def rvs_exponential(size):\n",
        "    return np.random.exponential(scale=1.0, size=size)  # lambda=1 => scale=1\n",
        "\n",
        "def rvs_pareto(alpha, xm, size):\n",
        "    # If Y ~ Pareto(alpha) with support y>=1 and pdf alpha*y^(-alpha-1)\n",
        "    # then X = xm*Y has pdf alpha*xm^alpha / x^(alpha+1), x>=xm\n",
        "    y = (1 + np.random.pareto(alpha, size=size))  # support y>=1\n",
        "    return xm * y\n",
        "\n",
        "def rvs_cauchy(size):\n",
        "    return stats.cauchy.rvs(loc=0, scale=1, size=size, random_state=None)\n",
        "\n",
        "DISTS = {\n",
        "    \"Uniform_0_1\": {\n",
        "        \"rvs\": rvs_uniform,\n",
        "        \"mean\": 0.5,\n",
        "        \"var\": 1/12\n",
        "    },\n",
        "    \"Exponential_lambda1\": {\n",
        "        \"rvs\": rvs_exponential,\n",
        "        \"mean\": 1.0,\n",
        "        \"var\": 1.0\n",
        "    },\n",
        "    \"Pareto_alpha3_xm1\": {\n",
        "        \"rvs\": lambda size: rvs_pareto(alpha=3.0, xm=1.0, size=size),\n",
        "        \"mean\": 1.5,   # 3/(3-1)\n",
        "        \"var\": 0.75    # 3/4\n",
        "    },\n",
        "    \"Pareto_alpha1p5_xm1\": {\n",
        "        \"rvs\": lambda size: rvs_pareto(alpha=1.5, xm=1.0, size=size),\n",
        "        \"mean\": 3.0,      # 1.5/(0.5)\n",
        "        \"var\": np.inf     # does not exist\n",
        "    },\n",
        "    \"Cauchy_0_1\": {\n",
        "        \"rvs\": rvs_cauchy,\n",
        "        \"mean\": None,     # undefined\n",
        "        \"var\": None       # undefined\n",
        "    }\n",
        "}\n",
        "\n",
        "# ---------- Helpers ----------\n",
        "def ensure_dir(path):\n",
        "    os.makedirs(path, exist_ok=True)\n",
        "\n",
        "def savefig(path):\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(path, dpi=200)\n",
        "    plt.close()\n",
        "\n",
        "# ---------- SLLN ----------\n",
        "def slln_analysis(dist_name, rvs_fn, out_dir, n=10000):\n",
        "    x = rvs_fn(n)\n",
        "    cum_mean = np.cumsum(x) / np.arange(1, n+1)\n",
        "\n",
        "    plt.figure()\n",
        "    plt.plot(cum_mean)\n",
        "    plt.xlabel(\"k\")\n",
        "    plt.ylabel(\"Cumulative mean\")\n",
        "    plt.title(f\"SLLN: Cumulative Mean - {dist_name}\")\n",
        "    savefig(os.path.join(out_dir, f\"slln_cummean_n{n}.png\"))\n",
        "\n",
        "# ---------- CLT ----------\n",
        "def clt_analysis(dist_name, rvs_fn, out_dir, mean, var, n_list=(2,5,10,30,50,100), m=1000):\n",
        "    for n in n_list:\n",
        "        # Generate m replications of sums\n",
        "        samples = rvs_fn((m, n))\n",
        "        sums = samples.sum(axis=1)\n",
        "\n",
        "        # Standardize if possible\n",
        "        if mean is not None and var is not None and np.isfinite(var):\n",
        "            z = (sums - n*mean) / np.sqrt(n*var)\n",
        "        else:\n",
        "            # If mean/var undefined, still visualize \"standardized-like\" by sample mean & std (for exploration)\n",
        "            z = (sums - np.mean(sums)) / (np.std(sums) + 1e-12)\n",
        "\n",
        "        # Histogram\n",
        "        plt.figure()\n",
        "        plt.hist(z, bins=30, density=True)\n",
        "        plt.title(f\"CLT Histogram - {dist_name} (n={n}, m={m})\")\n",
        "        plt.xlabel(\"Standardized sum\")\n",
        "        plt.ylabel(\"Density\")\n",
        "        savefig(os.path.join(out_dir, f\"clt_hist_n{n}_m{m}.png\"))\n",
        "\n",
        "        # Q-Q plot\n",
        "        plt.figure()\n",
        "        stats.probplot(z, dist=\"norm\", plot=plt)\n",
        "        plt.title(f\"Normal Q-Q - {dist_name} (n={n}, m={m})\")\n",
        "        savefig(os.path.join(out_dir, f\"clt_qq_n{n}_m{m}.png\"))\n",
        "\n",
        "def run_all(base_results=\"results\"):\n",
        "    ensure_dir(base_results)\n",
        "    for name, info in DISTS.items():\n",
        "        ddir = os.path.join(base_results, name)\n",
        "        ensure_dir(ddir)\n",
        "\n",
        "        # SLLN\n",
        "        slln_analysis(name, info[\"rvs\"], ddir, n=10000)\n",
        "\n",
        "        # CLT\n",
        "        clt_analysis(\n",
        "            name,\n",
        "            info[\"rvs\"],\n",
        "            ddir,\n",
        "            mean=info[\"mean\"],\n",
        "            var=info[\"var\"],\n",
        "            n_list=(2,5,10,30,50,100),\n",
        "            m=1000\n",
        "        )\n",
        "\n",
        "    print(\"Done. Check the results/ folder.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    run_all()"
      ],
      "metadata": {
        "id": "5kEpLLobQdYa",
        "outputId": "f391688b-41ba-4c68-e0b4-f5be37ce3e0c",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 20,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Done. Check the results/ folder.\n"
          ]
        }
      ]
    }
  ]
}
